language: c
os:
  - linux
  - osx
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin test operator-sdk $TRAVIS_BUILD_DIR 'operator-sdk version'
